const config = {
  CONTACT_PHONE_NUMBER: '',
  CONTACT_EMAIL: '',
  GOOGLE_MAPS_API_KEY: '',
  OFFICE_LOCATION_ADDRESS: '',
  OFFICE_LOCATION_COORDINATES: { lat: 0, lng: 0 },
  LINK_FACEBOOK: '',
  LINK_ISNTAGRAM: '',
  LINK_TELEGRAM: '',
  TELEGRAM_API_BOT_TOKEN: '',
  TELEGRAM_API_CHAT_ID: '',
};

export default config;
